### ISSUE TITLE
¿Falta algo?

### ISSUE THREAD

**Issue by fernand0** [JJ/Nuboso#1]
./md2epub 
pandoc: tuto-google-apps/README.md: openFile: does not exist (No such file or directory)

**Comment by JJ** [comment]
Tienes que descargar todos los submódulos.
O sea que sí falta algo: explicación de cómo hacerlo...

**Comment by fernand0** [comment]
git clone https://github.com/JJ/Nuboso.git
¿no es suficiente?

On Sun, Jan 18, 2015 at 7:56 PM, Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> Tienes que descargar todos los submódulos.
> O sea que sí falta algo: explicación de cómo hacerlo...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/Nuboso/issues/1#issuecomment-70420371.

## 

Fernando Tricas
http://elmundoesimperfecto.com/
